name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set login for Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker Image
      run: |
        pwsh build.ps1 -target build-docker

    - name: Push Docker Image
      run: |
        docker push kennethchoe/sql-crawler
